# Netlify設定ファイル
[build]
  # ビルドコマンドなし（静的サイト）
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200